bloodbankmanagement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LogoutView,LoginView
from blood import views
urlpatterns = [
    path('admin/', admin.site.urls),

    
    path('donor/',include('donor.urls')),
    path('patient/',include('patient.urls')),

    
    path('',views.home_view,name=''),
    path('logout', LogoutView.as_view(template_name='blood/logout.html'),name='logout'),

    path('afterlogin', views.afterlogin_view,name='afterlogin'),
    path('adminlogin', LoginView.as_view(template_name='blood/adminlogin.html'),name='adminlogin'),
    path('admin-dashboard', views.admin_dashboard_view,name='admin-dashboard'),
    path('admin-blood', views.admin_blood_view,name='admin-blood'),
    path('admin-donor', views.admin_donor_view,name='admin-donor'),
    path('admin-patient', views.admin_patient_view,name='admin-patient'),
    path('update-donor/<int:pk>', views.update_donor_view,name='update-donor'),
    path('delete-donor/<int:pk>', views.delete_donor_view,name='delete-donor'),
    path('admin-request', views.admin_request_view,name='admin-request'),
    path('update-patient/<int:pk>', views.update_patient_view,name='update-patient'),
    path('delete-patient/<int:pk>', views.delete_patient_view,name='delete-patient'),
    path('admin-donation', views.admin_donation_view,name='admin-donation'),
    path('approve-donation/<int:pk>', views.approve_donation_view,name='approve-donation'),
    path('reject-donation/<int:pk>', views.reject_donation_view,name='reject-donation'),
    path('admin-request-history', views.admin_request_history_view,name='admin-request-history'),
    path('update-approve-status/<int:pk>', views.update_approve_status_view,name='update-approve-status'),
    path('update-reject-status/<int:pk>', views.update_reject_status_view,name='update-reject-status'),
    path('send-email-and-message/', views.send_email_and_message, name='send_email_and_message'),
]

donor/218243P/Ecommerce/Ecommerce/myapp/urls.py
from django.urls import path
from myapp.views import order,index,detail,cart_view,return_view,cancel_view
app_name='myapp'

urlpatterns = [
 path('',index,name='index'),
 path('<int:product_id>/<slug:slug>',detail,name='detail'),
 path('cart/',cart_view,name='cart_view'),
 path('order/',order,name='order'),
 path('success/',return_view,name='return_view'),
 path('cancel/',cancel_view,name='cancel_view'),
]

donor/218243P/login/login/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

donor/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView
from . import views
urlpatterns = [
    path('donorlogin/', LoginView.as_view(template_name='donor/donorlogin.html'),name='donorlogin'),
    path('donorsignup/', views.donor_signup_view,name='donorsignup'),
    path('donor-dashboard/', views.donor_dashboard_view,name='donor-dashboard'),
    path('donate-blood/', views.donate_blood_view,name='donate-blood'),
    path('donate-blood/donation-history/', views.donation_history_view, name='donation_history'),
    path('make-request', views.make_request_view,name='make-request'),
    path('request-history', views.request_history_view,name='request-history'),
]

donor/218243P/Ecommerce/Ecommerce/myapp/models.py
from django.db import models

class Product(models.Model):
    title=models.CharField(max_length=100)
    description=models.TextField()
    slug=models.SlugField()
    price=models.DecimalField(max_digits=10,decimal_places=2)
    img=models.ImageField(upload_to='')
    
    def __str__(self):
        return self.title
class Cart(models.Model):
    cart_id=models.CharField(max_length=100)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    quantity=models.IntegerField()
    timestamp=models.DateTimeField(auto_now=True)
    product=models.ForeignKey(Product,on_delete=models.PROTECT)

    def __str__(self):
        return self.product.title
    def update_quantity(self,quantity):
        self.quantity+=quantity
        self.save()
    def total(self):
        return self.quantity*self.price
class Buy(models.Model):
        product=models.ForeignKey(Product,on_delete=models.PROTECT)
        quantity=models.IntegerField()
        price=models.DecimalField(max_digits=10,decimal_places=2)

        def __str__(self):
            return self.product.title+'_'+str(self.id) 

donor/218243P/Ecommerce/Ecommerce/myapp/forms.py
from django import forms

class CartForm(forms.Form):
    quantity=forms.IntegerField(initial='1')
    product_id=forms.IntegerField(widget=forms.HiddenInput)

    def __init__(self,request,*args,**kwargs):
        self.request=request
        super(CartForm,self).__init__(*args,**kwargs)

donor/218243P/Ecommerce/Ecommerce/myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from myapp.models import Product,Cart,Buy
from myapp.forms import CartForm
from myapp.myapp import *
from django.urls import reverse
from django.shortcuts import render
from paypal.standard.forms import PayPalPaymentsForm
# Create your views here.

def index(request):
    p=Product.objects.all()
    if request.GET.get('q'):
        query=request.GET.get('q')
        p=Product.objects.filter(title__contains=query)
    context={'p':p}
    return render(request,'index.html',context)
def detail(request,product_id,slug):
    d=Product.objects.get(id=product_id)
    if request.method=="POST":
        f=CartForm(request,request.POST)
        if f.is_valid():
            request.form_data=f.cleaned_data
            add_to_cart(request)
            return redirect('myapp:cart_view')

    f=CartForm(request,initial={'product_id':product_id})
    context={'d':d,'f':f}
    return render(request,'detail.html',context)
def cart_view(request):
    if request.method=="POST" and request.POST.get('delete')=='Delete':
        item_id=request.POST.get('item_id') 
        cd=Cart.objects.get(id=item_id)
        cd.delete()
    c=get_cart(request)
    t=total_(request)
    co=item_count(request)
    context={'c':c,'t':t}
    return render(request,'cart.html',context)
def order(request):
  # What you want the button to do.
  items=get_cart(request)
  for i in items:
    b=Buy(product_id=i.product_id,quantity=i.quantity,price=i.price)
    b.save()
    paypal_dict = {
        "business": "sb-u1vfe28146180@business.example.com",
        "amount": total_(request),
        "item_name": cart_id(request),
        "invoice": str(uuid.uuid4()),
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
        "return": request.build_absolute_uri(reverse('myapp:return_view')),
        "cancel_return": request.build_absolute_uri(reverse('myapp:cancel_view')),
        "custom": "premium_plan",  # Custom command to correlate to some function later (optional)
    }

    # Create the instance.
    form = PayPalPaymentsForm(initial=paypal_dict)
    context = {"form": form,"items":items,"total":total_(request)}
    return render(request, "order.html", context)
def return_view(request):
    return render(request,'transaction.html')
def cancel_view(request):
    return HttpResponse('Transaction Cancelled')

donor/218243P/Ecommerce/Ecommerce/myapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>  
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, 
    initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</head>
<body>
  
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#">Ecommerce</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Post</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" name="q" value="{{request.GET.q}}" placeholder="Search" aria-label="Search">
            <a href="{% url 'myapp:cart_view'%}"class="btn btn-outline-success my-2 my-sm-0">Cart</a>
          </form>
          <a class="btn btn-primary" href="#">Login</a>
          <a class="btn btn-primary" href="#">Register</a>
          <a class="btn btn-primary" href="#">Logout</a>
        
        </div>
      </nav>
  <div class="container">
    <br>
{% block content %}

{% endblock %}
</div>
</body
</html>

donor/218243P/Ecommerce/Ecommerce/myapp/templates/cart.html
{% extends 'base.html' %}
{% block content %}
<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Product</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Total Cost</th>
      </tr>
    </thead>
    <tbody>
        {% for i in c %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{i.product}}</td>
        <td>{{i.price}}</td>
        <td>{{i.quantity}}</td>
        <td>{{i.total}}</td>
        <td>
        <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="item_id" value="{{i.id}}">
            <input class="btn btn-danger" type="submit" name="delete" value="Delete">
        </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table><br>
  Total:₹{{t}}<br><br>
  <a class="btn btn-info" href="{% url 'myapp:order' %}">Order</a>
  &nbsp;&nbsp;&nbsp;
  <a class="btn btn-info" href="{% url 'myapp:index' %}">Back/Continue</a>  
  {% endblock %}

donor/218243P/Ecommerce/Ecommerce/myapp/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-6">
    <b>{{d.title}}</b><br>
    {{d.description}}<br>
    {{d.price}}<br>
    </div>
    <div class="col-md-6">
        <img src="{{d.img.url}}" widt=400 height="500">
    </div>

</div>
<form action="{% url 'myapp:detail' d.id d.slug %}" method="post">
    {% csrf_token %}
    {{ f }}
    <input type="submit" value="Add to Cart">
</form>
{% endblock %}

donor/218243P/Ecommerce/Ecommerce/myapp/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    {% for i in p %}
    <div class="col-md-6">
      <a href="{% url 'myapp:detail' i.id i.slug %}"><b>{{i.title}}</b></a><br>
      <img src="{{i.img.url}}" width=300 height=300 alt=""><br>
      ₹{{i.price}}
      <br><br>
      <style>
        body{
          background-color:lightcyan;

        }
      </style>
    </div>
    {% endfor %}
</div>
{% endblock %}

donor/218243P/Ecommerce/Ecommerce/myapp/templates/order.html
{% extends 'base.html' %}
{% block content %}
<b>Cart:</b><br>
{% for i in items %}
{{i.product}}<br>
{% endfor %}
Pay: {{total}}
<h1>Show me the money!</h1>
<!-- writes out the form tag automatically -->
{{ form.render }}
{% endblock %}

donor/218243P/Ecommerce/Ecommerce/myapp/templates/transaction.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><br><br><br><br>
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7fLGbTFZKIDyOeXJFQ3C16nwyt-qlL4iKyA&usqp=CAU" width="70" height="70">
    <h1>Order Placed</h1>
</center>
</body>
</html>